### ISSUE TITLE
Find a working version since Qt 5.15.2 and qt creator 4.15.0

### ISSUE THREAD

**Issue by RolfHausen** [trollixx/qtcreator-tabbededitor-plugin#27]
I have rebuild that to work with qt 5.15.2 and 4.15.0 start contributing on that fresh state so we get a better trace for this project.
here is the link. https://github.com/RolfHausen/qtcreator-TabbedEditor-plugin

@trollixx, if you come back to this project just join up, i respect your ownership on this project just extended it to get it back to usage. and i uploaded as a fresh project also cause i build it on a new qt creator plugin project and so filenames are different.

**Comment by lanmanck** [comment]
hi, I have this error with VS2017+QT5.14.1 64BIT (QC 4.11.1):
1\ Cannot read F:/qtcreatorplugin.pri: No such file or directory
2\ F:\WindowsDownload\qtcreator-TabbedEditor-plugin-main\tabbededitor.h:6: error: C1083: Cannot open include file: 'extensionsystem/iplugin.h': No such file or directory
3\ F:\WindowsDownload\qtcreator-TabbedEditor-plugin-main\tabbar.cpp:5: error: C1083: Cannot open include file: 'coreplugin/actionmanager/actionmanager.h': No such file or directory
